# Generated by Django 5.1.4 on 2025-01-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='groces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('Quality', models.CharField(max_length=255)),
                ('Vendor', models.CharField(max_length=255)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
